#%RAML 1.0
title: Customer 360 API
baseUri: https://mocksvc.mulesoft.com/mocks/41b3f3d0-9c47-4fa8-8179-130909b82b7b/{version} # baseUri: http://localhost/{version}
version: v3
description: This API spec design highlights the power of RAML. It reuses existing RAML fragments for dataTypes, traits, resourceTypes and more to simplify and accelerate definig an API Spec. Fragments also ENSURE CONSISTENCY acrosss APIs. With consistency comes acclerated delivery due to developers familiarity with the design fragments. Overlays and extensions are available if needed to modify the API fragments.  \nRAML allows you to define RAML DataTypes and RAML NamedExamples instead of defining a schema and example for JSON and another for schema and example for XML and then trying to keep them in sync. With RAML DataTypes and NamedExamples you can support JSON & XML from one DataType and one NamedExample.
    
mediaType: [application/json, application/xml]
securedBy: [passthrough]
securitySchemes: 
  passthrough: !include /exchange_modules/5dfb47dc-12e3-4cac-afc5-a00be32d15d8/pass-through-security-scheme/1.0.0/pass-through-security-scheme.raml

uses: 
  customer360: /exchange_modules/b2cc42af-8763-43cf-a316-246ce7aefd04/customer-360-library/1.0.6/customer-360-library.raml
  collectionRT: /exchange_modules/5dfb47dc-12e3-4cac-afc5-a00be32d15d8/collection-library/1.0.30/collection-library.raml
    
/customer360s:
  type:  
    collectionRT.collection:
  get:
    description: Since the traits were defined above, they can be referenced here
    queryParameters: 
      customerId?:
        minLength: 3
      customerName?:
        minLength: 3
      countryCode?:
        minLength: 3
        maxLength: 3
      orderId?:
        minLength: 3

  /{id}:
    type: 
      collectionRT.member:
    uriParameters: 
      id:
        example: "1"
        default: "1"
    get:

